# Generated by Django 6.0.3 on 2026-03-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarshanSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.IntegerField()),
                ('booked_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('full', 'Full')], default='open', max_length=20)),
            ],
            options={
                'db_table': 'darshan_slots',
            },
        ),
        migrations.CreateModel(
            name='Devotee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devotees',
            },
        ),
        migrations.CreateModel(
            name='Pooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'temples',
            },
        ),
        migrations.CreateModel(
            name='DarshanBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=100, unique=True)),
                ('num_people', models.IntegerField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.darshanslot')),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darshan_bookings', to='bookings.devotee')),
            ],
            options={
                'db_table': 'darshan_bookings',
            },
        ),
        migrations.CreateModel(
            name='PoojaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooja_bookings', to='bookings.devotee')),
                ('pooja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.pooja')),
            ],
        ),
        migrations.AddField(
            model_name='pooja',
            name='temple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poojas', to='bookings.temple'),
        ),
        migrations.AddField(
            model_name='darshanslot',
            name='temple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darshan_slots', to='bookings.temple'),
        ),
    ]
